#!/bin/bash

chown root:wheel /etc/Spotifyadblock
chmod 755 /etc/Spotifyadblock
chown root:wheel /etc/Spotifyadblock/minimalhosts
chmod 644 /etc/Spotifyadblock/minimalhosts
chown root:wheel /etc/Spotifyadblock/defaulthosts
chmod 644 /etc/Spotifyadblock/defaulthosts
echo "Overwriting hosts file..."
cp -a /etc/Spotifyadblock/minimalhosts /etc/hosts
echo "Overwrite complete!"
chown root:wheel /etc/hosts
chmod 644 /etc/hosts
echo "Killing discoveryd/mDNSResponder..."
killall -9 discoveryd
killall -9 mDNSResponder
echo "Should have died and restarted by now..."
echo "Deleting .git folder..."
rm -rf .git
echo ".git folder deleted!"
echo "Enjoy Spotify ad Blocker!"
echo "Please let me know if you find any ads!"
exit 0
